todo/schedule/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView

from . import views

app_name = 'schedule'

urlpatterns = [
	path('', views.signup, name='signup'),
	path('login', views.login, name='login'),
	path('logout', auth_views.LogoutView.as_view(), {'next_page': '/login'}, name='logout'),
	path('dashboard', views.dashboard , name='dashboard'),
	path('addSchedule', views.addSchedule, name='addSchedule'),
	path('updateSchedule/<int:id>', views.updateSchedule, name="updateSchedule"),
	path('deleteSchedule/<int:id>', views.deleteSchedule, name="deleteSchedule"),
	path('mark/<int:id>/<int:val>', views.mark, name="mark"),

]

todo/todo/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('schedule.urls', namespace='schedule')),
]

todo/schedule/models.py
from django.db import models
from django.contrib.auth.models import User

class Schedule(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100, null=False, blank=False)
    date = models.DateField(null=False, blank=False)
    start_time = models.TimeField(null=False, blank=False)
    end_time = models.TimeField(null=False, blank=False)
    done = models.BooleanField(default=False)

    def __str__(self):
        return str(self.user.username) + '\'s ' + str(self.title)

todo/schedule/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, logout, login as auth_login
from .models import *
import datetime

# Create your views here.
def signup(request):
    if request.method == 'GET':
        return render(request, 'authentication/signup.html')
    
    if request.method == 'POST':
        if User.objects.filter(username=request.POST.get('user_email')).count() > 0:
            messages.error(request, 'USER ALREADY EXISTS')
            return HttpResponseRedirect(reverse('schedule:signup'))
        else:
        	username = request.POST.get('user_name')
        	email = request.POST.get('user_email')
        	password = request.POST.get('user_password')
        	user = User.objects.create_user(username=username, email=email, password=password)
        	user.save()
        	messages.success(request, 'USER CREATED SUCCESSFULLY')
        	return HttpResponseRedirect(reverse('schedule:login'))

            

def login(request):
    if request.method == 'GET':
        if request.user.is_authenticated:
            return HttpResponseRedirect(reverse('schedule:dashboard'))
        return render(request, 'authentication/login.html')
    
    if request.method == 'POST':
        if User.objects.filter(username=request.POST.get('user_name')).count() == 0:
            messages.error(request, "NO SUCH USER FOUND")
            return HttpResponseRedirect(reverse('schedule:login'))
        else:
            username = request.POST.get('user_name')
            password = request.POST.get('user_password')
            user = authenticate(request, username=username, password=password)

            if user is not None:
                auth_login(request, user)
                messages.success(request, 'LOGIN SUCCESSFULL')
                return HttpResponseRedirect(reverse('schedule:dashboard'))
            else:
                messages.error(request, 'USERNAME/PASSWORD WRONG')
                return HttpResponseRedirect(reverse('schedule:login'))


#@login_required(login_url='/')
def dashboard(request):
	if request.user.is_authenticated:
	    upcoming_schedule_list = Schedule.objects.filter(user__username=request.user.username, date__gte=datetime.datetime.today())
	    previous_schedule_list = Schedule.objects.filter(user__username=request.user.username, date__lte=datetime.datetime.today())
	    return render(request, 'schedule/schedule.html', {'upcoming_schedule_list':upcoming_schedule_list, 'previous_schedule_list':previous_schedule_list})
	else:
		return HttpResponseRedirect(reverse('schedule:login'))

def addSchedule(request):
	if request.user.is_authenticated:
	    if request.method == 'GET':
	        return render(request, 'schedule/add-schedule.html')

	    if request.method == 'POST':
	        obj_schedule = Schedule()
	        obj_schedule.user = request.user
	        obj_schedule.title = request.POST.get('schedule_topic')
	        obj_schedule.date = request.POST.get('schedule_date')
	        obj_schedule.start_time = request.POST.get('schedule_start_time')
	        obj_schedule.end_time = request.POST.get('schedule_end_time')
	        start_time = request.POST.get('schedule_start_time')
	        end_time = request.POST.get('schedule_end_time')

	        if start_time.split(":")[0] > end_time.split(":")[0]:
	        	messages.success(request, 'Start time cannot be smaller than End time')
	        	return HttpResponseRedirect(reverse('schedule:addSchedule'))
	        elif start_time.split(":")[1] > end_time.split(":")[1]:
	        	messages.success(request, 'Start time cannot be smaller than End time')
	        	return HttpResponseRedirect(reverse('schedule:addSchedule'))
	        else:
	        	obj_schedule.save()
		        messages.success(request, 'SCHEDULE CREATED SUCCESSFULLY')
		        return HttpResponseRedirect(reverse('schedule:dashboard'))
	        print(start_time, end_time)        
	else:
		return HttpResponseRedirect(reverse('schedule:login'))


def updateSchedule(request, id):
	if request.user.is_authenticated:
	    if request.method == 'GET':
	        obj_schedule = get_object_or_404(Schedule, id=id)
	        return render(request, 'schedule/update-schedule.html', {'schedule':obj_schedule})

	    if request.method == 'POST':
	        obj_schedule = get_object_or_404(Schedule, id=id)
	        obj_schedule.topic = request.POST.get('schedule_topic')
	        obj_schedule.date = request.POST.get('schedule_date')
	        obj_schedule.start_time = request.POST.get('schedule_start_time')
	        obj_schedule.end_time = request.POST.get('schedule_end_time')
	        start_time = request.POST.get('schedule_start_time')
	        end_time = request.POST.get('schedule_end_time')

	        if start_time.split(":")[0] > end_time.split(":")[0]:
	        	messages.success(request, 'Start time cannot be smaller than End time')
	        	return HttpResponseRedirect(request.META['HTTP_REFERER'])
	        elif start_time.split(":")[1] > end_time.split(":")[1]:
	        	messages.success(request, 'Start time cannot be smaller than End time')
	        	return HttpResponseRedirect(request.META['HTTP_REFERER'])
	        else:
	        	obj_schedule.save()
		        messages.success(request, 'SCHEDULE CREATED SUCCESSFULLY')
		        return HttpResponseRedirect(reverse('schedule:dashboard'))
	else:
		return HttpResponseRedirect(reverse('schedule:login'))


def deleteSchedule(request, id):
	if request.user.is_authenticated:
	    if request.method == 'GET':
	        obj_schedule = get_object_or_404(Schedule, id=id)
	        obj_schedule.delete()
	        messages.success(request, 'SCHEDULE DELETED SUCCESSFULLY')
	        return HttpResponseRedirect(reverse('schedule:dashboard'))
	else:
		return HttpResponseRedirect(reverse('schedule:login'))

def mark(request, id, val):
	if request.user.is_authenticated:
	    if request.method == 'GET':
	        obj_schedule = get_object_or_404(Schedule, id=id)
	        obj_schedule.done = False if int(val) == 0 else True
	        obj_schedule.save()
 
	        if int(val) == 0:
	        	messages.success(request, "MARKED INCOMPLETE")
	        else:
	        	messages.success(request, "MARKED COMPLETE")
	        
	        return HttpResponseRedirect(reverse('schedule:dashboard'))
	else:
		return HttpResponseRedirect(reverse('schedule:login'))

todo/schedule/templates/authentication/login.html
<html>
    <head>
        <title>
            LOGIN
        </title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
       
    </head>
    <body>
        LOGIN FORM

        <br><br>
        {% if messages %}
        <ul>
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </ul>
        {% endif %}
        
        <form action="{% url 'schedule:login' %}" method="POST">
            {% csrf_token %}
            <label for="title">Username : </label>
            <input type="text" name="user_name" placeholder="Username" required class="form-control"><br>

            <label for="title">Password : </label>
            <input type="password" name="user_password" placeholder="Password" required class="form-control"><br>
            <button type="submit">LOGIN</button>
        </form>

        <br><br>
        <a href="{% url 'schedule:signup' %}">SIGNUP</a>
    </body>
</html>

todo/schedule/templates/authentication/signup.html
<html>
    <head>
        <title>
            SIGNUP
        </title>
    </head>
    <body>
        SIGNUP FORM

        <br><br>
        {% if messages %}
        <ul>
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </ul>
        {% endif %}

        <form action="{% url 'schedule:signup' %}" method="POST">
            {% csrf_token %}
            Name : <input type="text" name="user_name" placeholder="Your Name" required><br>
            Email : <input type="email" name="user_email" placeholder="Email" required><br>
            Password : <input type="password" name="user_password" placeholder="Password" required><br>
            <button type="submit">SIGNUP</button>
        </form>

        <br><br>
        <a href="{% url 'schedule:login' %}">LOGIN</a>
    </body>
</html>

todo/schedule/templates/schedule/add-schedule.html
{% extends 'Schedule/main.html' %}
{% block title %}ADD SCHEDULE{% endblock %}
{% block body %}
    
    <center><br>
        ADD SCHEDULE FORM
    <br><br>
    {% if messages %}
    <ul>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </ul>
    {% endif %}
    
    <form action="{% url 'schedule:addSchedule' %}" method="POST">
        {% csrf_token %}
        <label for="title">Title : </label>
        <input type="text" name="schedule_topic" placeholder="Title" required class="form-control"><br><br>

        <label for="title">Date : </label>
        <input type="date" name="schedule_date" placeholder="Date" required class="form-control"><br><br>

        <label for="title">Start Time : </label>
        <input type="time" name="schedule_start_time" placeholder="Start Time" required class="form-control"><br><br>

        <label for="title">End Time : </label>
        <input type="time" name="schedule_end_time" placeholder="End Time" required class="form-control"><br><br><br>
        <button type="submit" class="btn btn-success btn-block">ADD SCHEDULE</button>
    </form>

    <br><br>
    <a href="{% url 'schedule:dashboard' %}">Go back to Dashboard</a>
    </center>
{% endblock %}

todo/schedule/templates/schedule/main.html
<html>
    <head>
        <title>
            {% block title %}DASHBOARD{% endblock %}
        </title>
    </head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    {% block style %}
    <style>
        body {
            margin: 0;
            font-family: Arial, Helvetica, sans-serif;
        }
        
        .topnav {
            overflow: hidden;
            background-color: #333;
        }
        
        .topnav a {
            float: left;
            color: #f2f2f2;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }
        
        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }
        
        .topnav a.active {
            background-color: #4CAF50;
            color: white;
        }


#customers {
  font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

#customers td, #customers th {
  border: 1px solid #ddd;
  padding: 8px;
}

#customers tr:nth-child(even){background-color: #f2f2f2;}

#customers tr:hover {background-color: #ddd;}

#customers th {
  padding-top: 12px;
  padding-bottom: 12px;
  text-align: left;
  background-color: #512da8;
  color: white;
}
    </style>
    {% endblock %}
    <body>

        <div class="topnav">
            <a class="active" href="{% url 'schedule:dashboard' %}">Dashboard</a>
            <a href="{% url 'schedule:addSchedule' %}">Add Schedule</a>
            <li style="float:right"><a href="{% url 'schedule:logout' %}">LogOut</a></li>
        </div>
        <center>
        {% if messages %}
        <ul>
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </ul>
        {% endif %}
        </center>
        {% block body %}
        {% endblock %}
    </body>
    {% block scrpits %}
    {% endblock %}
</html>

todo/schedule/templates/schedule/schedule.html
{% extends 'schedule/main.html' %}
{% block title %}DASHBOARD{% endblock %}
{% block body %}
    <br><br>
    <center>
    ALL YOUR UPCOMING SCHEDULES
    <br><br>
    {% if upcoming_schedule_list %}
        <table id="customers">
            <thead>
                <th></th>
                <th>Name</th>
                <th>Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th colspan="2" style="text-align: center">Actions</th>
            </thead>
            <tbody>
                {% for schedule in upcoming_schedule_list %}
                    <tr>
                        <td><input type="checkbox" disabled {% if schedule.done %}checked{% endif %}></td>
                        <td>{{ schedule.title }}</td>
                        <td>{{ schedule.date }}</td>
                        <td>{{ schedule.start_time }}</td>
                        <td>{{ schedule.end_time }}</td>
                        <td>
                            {% if schedule.done %}
                                <a href="{% url 'schedule:mark' schedule.id 0 %}">MARK INCOMPLETE</a>
                            {% else %}
                                <a href="{% url 'schedule:mark' schedule.id 1 %}">MARK COMPLETE</a>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'schedule:updateSchedule' schedule.id %}">UPDATE</a>&nbsp;&nbsp;&nbsp;
                            <a href="{% url 'schedule:deleteSchedule' schedule.id %}">DELETE</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
    
    <br><br>
    ALL YOUR PREVIOUS SCHEDULES
    <br><br>
    {% if previous_schedule_list %}
        <table id="customers">
            <thead >
                <th></th>
                <th>Name</th>
                <th>Date</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th colspan="2" style="text-align: center">Actions</th>
            </thead>
            <tbody>
                {% for schedule in previous_schedule_list %}
                    <tr>
                        <td><input type="checkbox" disabled {% if schedule.done %}checked{% endif %}></td>
                        <td>{{ schedule.title }}</td>
                        <td>{{ schedule.date }}</td>
                        <td>{{ schedule.start_time }}</td>
                        <td>{{ schedule.end_time }}</td>
                        <td>
                            {% if schedule.done %}
                                <a href="{% url 'schedule:mark' schedule.id 0 %}">MARK INCOMPLETE</a>
                            {% else %}
                                <a href="{% url 'schedule:mark' schedule.id 1 %}">MARK COMPLETE</a>
                            {% endif %}
                        </td>
                        <td>
                            <a href="{% url 'schedule:updateSchedule' schedule.id %}">UPDATE</a>&nbsp;&nbsp;&nbsp;
                            <a href="{% url 'schedule:deleteSchedule' schedule.id %}">DELETE</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </center>
    {% endif %}
{% endblock %}

todo/schedule/templates/schedule/update-schedule.html
{% extends 'Schedule/main.html' %}
{% block title %}UPDATE SCHEDULE{% endblock %}
{% block body %}
    
    <center>
    <br>
    UPDATE SCHEDULE FORM<br><br>
    {% if messages %}
    <ul>
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </ul>
    {% endif %}
    
    <form action="{% url 'schedule:updateSchedule' schedule.id %}" method="POST">
        {% csrf_token %}
        <label for="title">Title : </label>
        <input type="text" name="schedule_topic" placeholder="Title" required value="{{schedule.title}}" class="form-control"><br>
        <br>
        <label for="title">Date : </label>
        <input type="date" name="schedule_date" placeholder="Date" required value="{{schedule.date|date:'Y-m-d'}}" class="form-control"><br><br>

        <label for="title">Start Time : </label>
        <input type="time" name="schedule_start_time" placeholder="Start Time" required value="{{schedule.start_time|date:'H:i'}}" class="form-control"><br><br>

        <label for="title">End Time : </label>
        <input type="time" name="schedule_end_time" placeholder="End Time" required value="{{schedule.end_time|date:'H:i'}}" class="form-control"><br>
        <br><br>
        <button type="submit" class="btn btn-success btn-block">UPDATE SCHEDULE</button>
    </form>

    <br><br>
    <a href="{% url 'schedule:dashboard' %}">Go back to Dashboard</a>
    </center>
{% endblock %}

todo/todo/templates/signup.html
<html>
    <head>
        <title>
            SIGNUP
        </title>
    </head>
    <body>
        SIGNUP FORM

        <br><br>
        {% if messages %}
        <ul>
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </ul>
        {% endif %}

        <form action="{% url 'UserAuth:signup' %}" method="POST">
            {% csrf_token %}
            Email : <input type="email" name="user_email" placeholder="Email" required><br>
            Password : <input type="password" name="user_password" placeholder="Password" required><br>
            First Name : <input type="text" name="user_first_name" placeholder="First Name" required><br>
            Last Email : <input type="text" name="user_last_name" placeholder="Last Name" required><br>
            <button type="submit">SIGNUP</button>
        </form>

        <br><br>
        <a href="{% url 'UserAuth:login' %}">LOGIN</a>
    </body>
</html>